// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Token struct {
	Hash   []byte
	UserID int64
	Expiry pgtype.Timestamptz
	Scope  string
}

type User struct {
	UserPid      int64
	Username     string
	Email        string
	Name         pgtype.Text
	PasswordHash []byte
	Bio          pgtype.Text
	Activated    bool
	ProfilePic   pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Version      int32
}
